config/routes.rb
WebRecorder::Application.routes.draw do
  get "top/index"
  root to: "top#index"
  get "about" => "top#about", as: "about"
  
  resources :teams do
    collection {get "search"}
  end

  resources :matches do
    collection {get "search"}
  end
  
  resources :records

end

app/models/match.rb
class Match < ActiveRecord::Base
  has_many :records
  has_and_belongs_to_many :teams

  validates :matchid,
    presence: true,
    length: { minimum: 5, maximum: 20, allow_blank: true }

#  def name
#    if (self.teams.all.first && self.teams.all.second)
#      self.teams.first.name + " vs. " + self.teams.second.name
#    end
#  end
  
  class << self
  def search(query)
      rel = order("name")
      if query.present?
        rel = rel.where("name LIKE ?", "%#{query}%")
      end
      rel
    end
  end

end

app/models/matches_teams.rb
class MatchesTeams < ActiveRecord::Base
end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :match
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_and_belongs_to_many :matches
  has_one :image, class_name: "TeamImage", dependent: :destroy

  validates :name,
    presence: true,
    length: { minimum: 1, maximum: 20, allow_blank: true }

  class << self
    def search(query)
      rel = order("name")
      if query.present?
        rel = rel.where("name LIKE ?", "%#{query}%")
      end
      rel
    end
  end

end

app/models/team_image.rb
class TeamImage < ActiveRecord::Base
  belongs_to :team
  
  #  validate :check_image
  
  #  attr_accessible :uploaded_image
  #  attr_accessible :uploaded_image, as: :admin
  #  attr_accessor :uploaded_image

  IMAGE_TYPES = { "image/jpeg" => "jpg", "image/gif" => "gif",
  "image/png" => "png" }

  def extension
    IMAGE_TYPES[content_type]
  end
  
  private
  def convert_content_type(ctype)
      ctype = ctype.rstrip.downcase
      case ctype
          when "image/pjpeg" then "image/jpeg"
          when "image/jpg"   then "image/jpeg"
          when "image/x-png" then "image/png"
          else ctype
      end
  end

  def check_image
    if @uploaded_image
      if data.size > 64.kilobytes
          errors.add(:uploaded_image, :too_big_image)
      end
      unless IMAGE_TYPES.has_key?(content_type)
          errors.add(:uploaded_image, :invalid_image)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_filter :verify_authenticity_token
end

app/controllers/matches_controller.rb
# cording: utf-8

class MatchesController < ApplicationController

  def index
    @matches = Match.all
  end
    
  def show
    @match = Match.find(params[:id])
    #@teams = @match.teams.all
    #@records = @match.records.all
    #@records1st = @match.records.where(half: 1).order(:recordtime)
    #@records2nd = @match.records.where(half: 2).order(:recordtime)
    #@records1st = Record.where(match: @match, half: 1)
    #@records2nd = Record.where(match: @match, half: 2)
  end
    
  def new
    @match = Match.new
    @teams = Team.all
  end
    
 def edit
    @match = Match.find(params[:id])
    @teams = Team.all
 end
    
 def create
    permitted_params = params.require(:match).permit(:matchid, :date)
    @match = Match.create(permitted_params)
    @match.teams << Team.find(params[:team0])
    @match.teams << Team.find(params[:team1])
    @match.name = @match.teams.first.name + " vs. " + @match.teams.second.name
    if @match.save
#      redirect_to @match, notice: "New match registered."
        redirect_to :matches, notice: "New match registered."
    else
      @allteams = Team.all
      render "new"
    end
  end
    
  def update
    @match = Match.find(params[:id])
    #    @match.assign_attributes(params[:match])
    permitted_params = params.require(:match).permit(:matchid, :date)
    @match.update_attributes(permitted_params)
    @match.teams.delete_all
    @match.teams << Team.find(params[:team0])
    @match.teams << Team.find(params[:team1])
    @match.name = @match.teams.first.name + " vs. " + @match.teams.second.name
    if @match.save
      redirect_to @match, notice: "Match profile is updated."
#      redirect_to :matches, notice: "Match profile is updated."
    else
      @allteams = Team.all
      render "edit"
    end
  end
    
  def destroy
    @match = Match.find(params[:id])
    @match.destroy
    redirect_to :matches, notice: "Match deleted!"
  end
    
# 検索
  def search
    @matchs = Match.search(params[:q]).
    paginate(page: params[:page], per_page: 15)
    render "index"
  end
end

app/controllers/records_controller.rb
# cording: utf-8

class RecordsController < ApplicationController

  def index
    @records = Record.all
  end
    
  def show
    @record = Record.find(params[:id])
  end
    
  def new
    @record = Record.new
    @matches = Match.all
  end
    
 def edit
    @record = Record.find(params[:id])
    @matches = Match.all
 end
    
 def create
    permitted_params = params.require(:record).permit(:match_id, :team, :event, :half, :recordtime)
    @record = Record.create(permitted_params)
    if (@record.match && @record.save)
      redirect_to @record.match, notice: "New record."
    else
      render "new"
    end
  end
    
  def update
    @record = Record.find(params[:id])
    permitted_params = params.require(:record).permit(:match_id, :team, :event, :half, :recordtime)
    @record.update_attributes(permitted_params)
    if (@record.match && @record.save)
      redirect_to @record.match, notice: "Record is updated."
    else
      render "edit"
    end
  end
    
  def destroy
    @record = Record.find(params[:id])
    @record.destroy
    redirect_to :records, notice: "Record deleted!"
  end
end

app/controllers/teams_controller.rb
# cording: utf-8

class TeamsController < ApplicationController

  def index
    @teams = Team.order("name")
  end

  def show
    @team = Team.find(params[:id])
    if params[:format].in?(["jpg", "png", "gif"])
      send_image
      #    else
      #render "teams/show"
    end
  end

  def new
    @team = Team.new
  end

  def edit
    @team = Team.find(params[:id])
  end

  def create
    permitted_params = params.require(:team).permit(:name, :hometown, :stadium)
    @team = Team.create(permitted_params)
    if @team.save
#      redirect_to @team, notice: "New team registered."
      redirect_to :teams, notice: "New team registered."
    else
      render "new"
    end
  end

  def update
    @team = Team.find(params[:id])
    permitted_params = params.require(:team).permit(:name, :hometown, :stadium)
    @team.update_attributes(permitted_params)
    if @team.save
#        redirect_to @team, notice: "Team profile is updated."
        redirect_to :teams, notice: "Team profile is updated."
    else
      render "edit"
    end
  end

  def destroy
    @team = Team.find(params[:id])
    @team.destroy
    redirect_to :teams, notice: "Team deleted!"
  end

# 検索
  def search
    @teams = Team.search(params[:q]).
    paginate(page: params[:page], per_page: 15)
    render "index"
  end

  private
  # 画像送信
  def send_image
    if @team.image.present?
      send_data @team.image.data,
      type: @team.image.content_type, disposition: "inline"
    else
      raise NotFound
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def page_title
        title = "WebRecorder"
        title = @page_title + " - " + title if @page_title
        title
    end
    
    def menu_link_to(text, path)
        link_to_unless_current(text, path) { content_tag(:span, text) }
    end
    
    def team_image_tag(team, options = {})
        if team.image.present?
            path = team_path(team, format: team.image.extension)
            link_to(image_tag(path, { alt: team.name }.merge(options)), path)
        else
            ""
        end
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <title><%= page_title %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
  <div id="header">
<%= render "shared/header" %>
  </div>
  <div id="content">
<% if flash.notice %>
<p class="notice"><%= flash.notice %></p>
<% end %>

<%= yield %>
  </div>
  <div id="sidebar">
<%= render "shared/sidebar" %>
  </div>
  <div id="footer">
<%= render "shared/footer" %>
  </div>
</div>

</body>
</html>

app/views/matches/_form.html.erb
<%= render "shared/errors", obj: @match %>

<table class="attr">
  <tr>
    <th><%= form.label :name, "ID" %></th>
    <td><%= form.text_field :matchid %></td>
  </tr>
  <tr>
    <th><%= label_tag "チームA" %></th>
    <td><%= select_tag :team0, options_from_collection_for_select(@teams, :id, :name, (@match.teams.present? ? @teams.index(@match.teams.first) : 0)+1) %></td>
  </tr>
  <tr>
    <th><%= label_tag "チームB" %></th>
    <td><%= select_tag :team1, options_from_collection_for_select(@teams, :id, :name, (@match.teams.present? ? @teams.index(@match.teams.second) : 0)+1) %></td>
  </tr>
</table>

app/views/matches/edit.html.erb
<% @page_title = "試合情報の編集" %>

<h1><%= @page_title %></h1>

<p><%= link_to "試合の詳細に戻る", @match %></p>

<%= form_for @match do |form| %>
<%= render "form", form: form %>
<p><%= form.submit %></p>
<% end %>

app/views/matches/index.html.erb
<% @page_title = "試合" %>

<h1><%= @page_title %></h1>

<%= form_tag :search_matches, method: :get do %>
<p><%= text_field_tag "q", params[:q] %>
<%= submit_tag "検索" %></p>
<% end %>

<p><%= link_to "試合の登録", :new_match %></p>

<% if @matches.present? %>
<table class="list">
  <tr>
  　<th>HOME</th>
    <th>対戦カード</th>
    <th>AWAY</th>
    <th>操作</th>
  </tr>
  <% @matches.each do |match| %>
  <tr>
    <td align="center"><%= team_image_tag match.teams.all.first, width: 24 if match.teams.all.first %></td>
    <td align="center"><%= link_to match.name, match %></td>
    <td align="center"><%= team_image_tag match.teams.all.second, width: 24 if match.teams.all.second %></td>
    <td>
      <%= link_to "編集", [:edit, match] %> |
      <%= link_to "削除", match, method: :delete,
            confirm: "本当に削除しますか?" %>
    </td>
  </tr>
  <% end %>
</table>
<% else %>
<p>試合が登録されていません。</p>
<% end %>

app/views/matches/new.html.erb
<% @page_title = "試合の新規登録" %>

<h1><%= @page_title %></h1>

<%= form_for @match do |form| %>
<%= render "form", form: form %>
<p><%= form.submit %></p>
<% end %>

app/views/matches/show.html.erb
<% @page_title = @match.name %>
<%= javascript_include_tag "http://d3js.org/d3.v3.min.js" %>

<h1><%= @page_title %></h1>

<p><%= link_to "編集", [:edit, @match] %></p>

<table class="attr">
  <tr>
    <th>前半</th>
    <td><%= @match.teams.order(:id).first.name %></td>
  </tr>
  <% @match.records.where(team: 0, half: 1).order(:recordtime).each do |record| %>
  <tr>
    <th><%= record.recordtime %> min.</th>
    <td><%= link_to record.event ,record %></td>
  </tr>
  <% end %>
</table>

<table class="attr">
  <tr>
    <th>前半</th>
    <td><%= @match.teams.order(:id).second.name %></td>
  </tr>
  <% @match.records.where(team: 1, half: 1).order(:recordtime).each do |record| %>
  <tr>
    <th><%= record.recordtime %> min.</th>
    <td><%= link_to record.event, record %></td>
  </tr>
  <% end %>
</table>

<table class="attr">
  <tr>
    <th>後半</th>
    <td><%= @match.teams.order(:id).first.name %></td>
  </tr>
  <% @match.records.where(team: 0, half: 2).order(:recordtime).each do |record| %>
  <tr>
    <th><%= record.recordtime %> min.</th>
    <td><%= link_to record.event ,record %></td>
  </tr>
  <% end %>
</table>

<table class="attr">
  <tr>
    <th>後半</th>
    <td><%= @match.teams.order(:id).second.name %></td>
  </tr>
  <% @match.records.where(team: 1, half: 2).order(:recordtime).each do |record| %>
  <tr>
    <th><%= record.recordtime %> min.</th>
    <td><%= link_to record.event, record %></td>
  </tr>
  <% end %>
</table>

<table class="attr">
  <tr>
    <th> 追加 </th>
    <td><%= link_to "[ NEW RECORD ]", new_record_path %></td>
  </tr>
</table>

<table class="attr">
  <tr>
    <th><%= @match.teams.order(:id).first.name %>:</th><td id="team0"></td>
  </tr>
  <tr>
    <th><%= @match.teams.order(:id).second.name %>:</th><td id="team1"></td>
  </tr>
</table>

    <script type="text/javascript">
        //Width and height
        var w = 400; var dx = w*0.9/50;
        var h =  60;
        var s =   1;

        var data0 = <%= @match.records.where(team: 0, half: 1).order(:recordtime).map(&:recordtime) %>;
        var data1 = <%= @match.records.where(team: 1, half: 1).order(:recordtime).map(&:recordtime) %>;

        //Create SVG element
        var svg0 = d3.select("#team0")
                     .append("svg")
                     .attr("width", w)
                     .attr("height", h);
        var svg1 = d3.select("#team1")
                     .append("svg")
                     .attr("width", w)
                     .attr("height", h);

        svg0.selectAll("path")
            .data(data0)
            .enter()
            .append("path")
            .attr("d", function(d) {return "M "+(d*dx)+" 0 L "+(d*dx)+" "+h;})
            .attr("stroke", "green")
            .attr("stroke-width", s);
        svg1.selectAll("path")
            .data(data1)
            .enter()
            .append("path")
            .attr("d", function(d) {return "M "+(d*dx)+" 0 L "+(d*dx)+" "+h;})
            .attr("stroke", "green")
            .attr("stroke-width", s);
    </script>

app/views/records/_form.html.erb
<%= render "shared/errors", obj: @record %>

<table class="attr">
  <tr>
    <th><%= label_tag "試合" %></th>
    <td><%= form.collection_select(:match_id, @matches, :id, :name) %>
    </td>
  </tr>
    <tr>
    <th><%= label_tag "チーム" %></th>
    <td><%= form.select(:team, {"Home" => 0, "Away" => 1}) %></td>
  </tr>
  <tr>
    <th><%= label_tag "event" %></th>
    <td><%= form.select(:event, ['PASS', 'DRIBBLE', 'SHOT', 'GOAL']) %></td>
  </tr>
  <tr>
    <th><%= label_tag "前・後半" %></th>
    <td><%= form.select(:half, {'前半' => 1, '後半' => 2}) %></td>
  </tr>
  <tr>
    <th><%= label_tag "時刻" %></th>
    <td><%= form.select(:recordtime, Array.new(56) {|i| i }) %></td>
  </tr>
</table>

app/views/records/edit.html.erb
<% @page_title = "記録の編集" %>

<h1><%= @page_title %></h1>

<p><%= link_to "記録の詳細に戻る", @record %></p>

<%= form_for @record do |form| %>
<%= render "form", form: form %>
<p><%= form.submit %></p>
<% end %>

app/views/records/new.html.erb
<% @page_title = "新規（イベント）記録" %>

<h1><%= @page_title %></h1>

<%= form_for @record do |form| %>
<%= render "form", form: form %>
<p><%= form.submit %></p>
<% end %>

app/views/records/show.html.erb
<% @page_title = "記録の詳細" %>

<h1><%= @page_title %></h1>

<p><%= link_to "編集", [:edit, @record] %></p>

<table class="attr">
  <tr>
    <th>試合</th>
    <td><%= link_to @record.match.name, @record.match %></td>
  </tr>
  <tr>
    <th>チーム</th>
    <td><%= if (@record.team == 0) then 
                @record.match.teams.first.name
            else 
                @record.match.teams.second.name 
            end %>
    </td>
  </tr>
  <tr>
    <th>イベント</th>
    <td><%= @record.event %></td>
  </tr>
  <tr>
    <th>時刻</th>
    <td><%= (@record.half == 1) ? "前半" : "後半"%> <%= @record.recordtime %> min.</td>
  </tr>
</table>

app/views/shared/_errors.html.erb
<% unless obj.errors.empty? %>
<div id="errors">
<h2>エラーがあります。</h2>
<ul>
  <% obj.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
  <% end %>
</ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%= link_to "このサイトについて", about_path %> |
Copyright (C) <%= link_to "Oiax Inc.", "http://www.oiax.co.jp/" %>
2007-2012

app/views/shared/_header.html.erb
<%= image_tag("logo.gif", size: "272x48", alt: "Morning Glory") %>

<div class="menubar">
<%= menu_link_to "TOP", root_path %> &nbsp;|&nbsp;
<%= menu_link_to "試合", :matches %> &nbsp;|&nbsp;
<%= menu_link_to "チームリスト", :teams %> &nbsp;|&nbsp;
<%= menu_link_to "管理ページ", "#" %>
</div>

app/views/shared/_login_form.html.erb
<h2>ログイン</h2>
<table id="login_form">
<tr>
<td align="right">ユーザー名：</td>
<td><input type="text" size="16" style="width: 120px" /></td>
</tr>
<tr>
<td align="right">パスワード：</td>
<td><input type="password" size="16" style="width: 120px" /></td>
</tr>
<tr>
<td colspan="2" align="center">
<input type="submit" value="ログイン" /></td>
</tr>
</table>

app/views/shared/_sidebar.html.erb
<%= render "shared/login_form" %>

<h2>最新の投稿</h2>
<ul>
<% 5.times do |i| %>
<li><%= link_to "ニュースの見出し", "#" %></li>
<% end %>
</ul>
<h2>試合履歴</h2>
<ul>
<% 5.times do |i| %>
<li><%= link_to "ブログの見出し", "#" %></li>
<% end %>
</ul>

app/views/top/index.html.erb
<h1>HELLO</h1>
<p> This is top page of webRecorder </p>